In [1]:
from __future__ import print_function

import numpy as np

import regreg.api as rr

from scipy.stats import norm

from selectinf.query import gaussian_query

from selectinf.randomization import randomization

from selectinf.Utils.base import (restricted_estimator,
                                  _compute_hessian)

/Users/yilingh/Desktop/PhD/SI_Codes/SI-Graphs/env3/lib/python3.10/site-packages/regreg/atoms/slope.py:16: UserWarning: unable to import isotonic regression from sklearn, using a pure python implementation
  warn('unable to import isotonic regression from sklearn, using a pure python implementation')


In [3]:
a = np.zeros((3,5))

In [4]:
b = np.delete(a, 1, axis=1)

In [25]:
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
norm.cdf(1.96)

0.9750021048517795

In [35]:
def Phi(t):
    return norm.cdf(t)
def Phi_tilde(t):
    return 1-Phi(t)
def Phi_inv(a):
    return norm.ppf(a)
def Phi_tilde_inv(a):
    return -norm.ppf(a)

In [36]:
Phi_tilde_inv(Phi_tilde(0))

-0.0

In [5]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.array([7,8,9])
a = []
a.append(a1)
a.append(a2)
a.append(a3)
a = np.asarray(a)

In [7]:
print(a[1])

[4 5 6]
